import os


def get_symbols(preprocess_path):
    filenames = ["train.txt", "val.txt", "test.txt"]
    text_seq = []
    for filename in filenames:
        with open(os.path.join(preprocess_path, filename), "r", encoding="utf-8") as f:
            for line in f.readlines():
                _, __, ___, ____, text, = line.strip("\n").split("|")
                text_seq += [t for t in list(
                    text.replace("{", "").replace("}", ""))]
    text_seq = list(set(text_seq))
    text_seq.sort()

    symbol_to_id = {s: i+1 for i, s in enumerate(text_seq)}
    return symbol_to_id


def get_kata2phoneme():
    voca = {
        "ウ゛ァ": "b a",
        "ウ゛ィ": "b i",
        "ウ゛ェ": "b e",
        "ウ゛ォ": "b o",
        "ウ゛ュ": "by u",
        "ヴァ": "b a",
        "ヴィ": "b i",
        "ヴェ": "b e",
        "ヴォ": "b o",
        "ヴュ": "by u",
        "ヴ": "b u",

        "ゥ゛": "b u",

        "アァ": "a a",
        "イィ": "i i",
        "イェ": "i e",
        "イャ": "y a",
        "ウゥ": "u",
        "エェ": "e e",
        "オォ": "o o",
        "カァ": "k a a",
        "キィ": "k i i",
        "クゥ": "k u u",
        "クャ": "ky a",
        "クュ": "ky u",
        "クョ": "ky o",
        "ケェ": "k e e",
        "コォ": "k o o",
        "ガァ": "g a a",
        "ギィ": "g i i",
        "グゥ": "g u u",
        "グャ": "gy a",
        "グュ": "gy u",
        "グョ": "gy o",
        "ゲェ": "g e e",
        "ゴォ": "g o o",
        "サァ": "s a a",
        "シィ": "sh i i",
        "スゥ": "s u u",
        "スャ": "sh a",
        "スュ": "sh u",
        "スョ": "sh o",
        "セェ": "s e e",
        "ソォ": "s o o",
        "ザァ": "z a a",
        "ジィ": "j i i",
        "ズゥ": "z u u",
        "ズャ": "zy a",
        "ズュ": "zy u",
        "ズョ": "zy o",
        "ゼェ": "z e e",
        "ゾォ": "z o o",
        "タァ": "t a a",
        "チィ": "ch i i",
        "ツァ": "ts a",
        "ツィ": "ts i",
        "ツゥ": "ts u u",
        "ツャ": "ch a",
        "ツュ": "ch u",
        "ツョ": "ch o",
        "ツェ": "ts e",
        "ツォ": "ts o",
        "テェ": "t e e",
        "トォ": "t o o",
        "ダァ": "d a a",
        "ヂィ": "j i i",
        "ヅゥ": "d u u",
        "ヅャ": "zy a",
        "ヅュ": "zy u",
        "ヅョ": "zy o",
        "デェ": "d e e",
        "ドォ": "d o o",
        "ナァ": "n a a",
        "ニィ": "n i i",
        "ヌゥ": "n u u",
        "ヌャ": "ny a",
        "ヌュ": "ny u",
        "ヌョ": "ny o",
        "ネェ": "n e e",
        "ノォ": "n o o",
        "ハァ": "h a a",
        "ヒィ": "h i i",
        "フゥ": "f u u",
        "フャ": "hy a",
        "フュ": "hy u",
        "フョ": "hy o",
        "ヘェ": "h e e",
        "ホォ": "h o o",
        "バァ": "b a a",
        "ビィ": "b i i",
        "ブゥ": "b u u",
        "フャ": "hy a",
        "ブュ": "by u",
        "フョ": "hy o",
        "ベェ": "b e e",
        "ボォ": "b o o",
        "パァ": "p a a",
        "ピィ": "p i i",
        "プゥ": "p u u",
        "プャ": "py a",
        "プュ": "py u",
        "プョ": "py o",
        "ペェ": "p e e",
        "ポォ": "p o o",
        "マァ": "m a a",
        "ミィ": "m i i",
        "ムゥ": "m u u",
        "ムャ": "my a",
        "ムュ": "my u",
        "ムョ": "my o",
        "メェ": "m e e",
        "モォ": "m o o",
        "ヤァ": "y a a",
        "ユゥ": "y u u",
        "ユャ": "y a a",
        "ユュ": "y u u",
        "ユョ": "y o o",
        "ヨォ": "y o o",
        "ラァ": "r a a",
        "リィ": "r i i",
        "ルゥ": "r u u",
        "ルャ": "ry a",
        "ルュ": "ry u",
        "ルョ": "ry o",
        "レェ": "r e e",
        "ロォ": "r o o",
        "ワァ": "w a a",
        "ヲォ": "o o",

        "ウ゛": "b u",
        "ディ": "d i",
        "デェ": "d e e",
        "デャ": "dy a",
        "デュ": "dy u",
        "デョ": "dy o",
        "ティ": "t i",
        "テェ": "t e e",
        "テャ": "ty a",
        "テュ": "ty u",
        "テョ": "ty o",
        "スィ": "s i",
        "ズァ": "z u a",
        "ズィ": "z i",
        "ズゥ": "z u",
        "ズャ": "zy a",
        "ズュ": "zy u",
        "ズョ": "zy o",
        "ズェ": "z e",
        "ズォ": "z o",
        "キャ": "ky a",
        "キュ": "ky u",
        "キョ": "ky o",
        "シャ": "sh a",
        "シュ": "sh u",
        "シェ": "sh e",
        "ショ": "sh o",
        "チャ": "ch a",
        "チュ": "ch u",
        "チェ": "ch e",
        "チョ": "ch o",
        "トゥ": "t u",
        "トャ": "ty a",
        "トュ": "ty u",
        "トョ": "ty o",
        "ドァ": "d o a",
        "ドゥ": "d u",
        "ドャ": "dy a",
        "ドュ": "dy u",
        "ドョ": "dy o",
        "ドォ": "d o o",
        "ニャ": "ny a",
        "ニュ": "ny u",
        "ニョ": "ny o",
        "ヒャ": "hy a",
        "ヒュ": "hy u",
        "ヒョ": "hy o",
        "ミャ": "my a",
        "ミュ": "my u",
        "ミョ": "my o",
        "リャ": "ry a",
        "リュ": "ry u",
        "リョ": "ry o",
        "ギャ": "gy a",
        "ギュ": "gy u",
        "ギョ": "gy o",
        "ヂェ": "j e",
        "ヂャ": "j a",
        "ヂュ": "j u",
        "ヂョ": "j o",
        "ジェ": "j e",
        "ジャ": "j a",
        "ジュ": "j u",
        "ジョ": "j o",
        "ビャ": "by a",
        "ビュ": "by u",
        "ビョ": "by o",
        "ピャ": "py a",
        "ピュ": "py u",
        "ピョ": "py o",
        "ウァ": "u a",
        "ウィ": "w i",
        "ウェ": "w e",
        "ウォ": "w o",
        "ファ": "f a",
        "フィ": "f i",
        "フゥ": "f u",
        "フャ": "hy a",
        "フュ": "hy u",
        "フョ": "hy o",
        "フェ": "f e",
        "フォ": "f o",

        "ア": "a",
        "イ": "i",
        "ウ": "u",
        "エ": "e",
        "オ": "o",
        "カ": "k a",
        "キ": "k i",
        "ク": "k u",
        "ケ": "k e",
        "コ": "k o",
        "サ": "s a",
        "シ": "sh i",
        "ス": "s u",
        "セ": "s e",
        "ソ": "s o",
        "タ": "t a",
        "チ": "ch i",
        "ツ": "ts u",
        "テ": "t e",
        "ト": "t o",
        "ナ": "n a",
        "ニ": "n i",
        "ヌ": "n u",
        "ネ": "n e",
        "ノ": "n o",
        "ハ": "h a",
        "ヒ": "h i",
        "フ": "f u",
        "ヘ": "h e",
        "ホ": "h o",
        "マ": "m a",
        "ミ": "m i",
        "ム": "m u",
        "メ": "m e",
        "モ": "m o",
        "ラ": "r a",
        "リ": "r i",
        "ル": "r u",
        "レ": "r e",
        "ロ": "r o",
        "ガ": "g a",
        "ギ": "g i",
        "グ": "g u",
        "ゲ": "g e",
        "ゴ": "g o",
        "ザ": "z a",
        "ジ": "j i",
        "ズ": "z u",
        "ゼ": "z e",
        "ゾ": "z o",
        "ダ": "d a",
        "ヂ": "j i",
        "ヅ": "z u",
        "デ": "d e",
        "ド": "d o",
        "バ": "b a",
        "ビ": "b i",
        "ブ": "b u",
        "ベ": "b e",
        "ボ": "b o",
        "パ": "p a",
        "ピ": "p i",
        "プ": "p u",
        "ペ": "p e",
        "ポ": "p o",
        "ヤ": "y a",
        "ユ": "y u",
        "ヨ": "y o",
        "ワ": "w a",
        "ヰ": "i",
        "ヱ": "e",
        "ン": "N",
        "ッ": "cl",

        "ァ": "a",
        "ィ": "i",
        "ゥ": "u",
        "ェ": "e",
        "ォ": "o",
        "ヮ": "w a",
        "ォ": "o",

        "ャ": "y a",
        "ュ": "y u",
        "ョ": "y o",

        "ヵ": "k a",
        "ㇱ": "sh i",
        "ㇲ": "s u",

        "ㇻ": "r a",
        "ㇼ": "r i",
        "ㇽ": "r u",

        "ヲ": "o",

        "ー": "ー",
    }
    return voca
