dataset: "rwcp-ssd"

path:
  corpus_data_path: "./corpus/RWCP-SSD" # common setting
  formatted_data_path: "./formatted_data/RWCP-SSD" # common setting
  preprocessed_data_path: "./preprocessed_data/RWCP-SSD" # image in "*/image", mel in "*/mel"
  font_path: "./font/ipaexg00401/ipaexg.ttf" # common setting

preprocessing:
  extract_label: ['coffmill', 'cup1', 'clock1', 'whistle3', 'maracas', 'drum', 'shaver', 'trashbox', 'tear', 'bells5'] # common setting
  notuse_train_audio_num: [13, 33, 53, 73, 93] # common setting
  input_type: "visual-text" # support "visual-text" or "katakana" or "phoneme"
  confidence_score_border: 3 # >= confidence_score_border
  acceptance_score_border: 2.5 # >= acceptance_score_border
  text:
    font_size: 24 # common setting
  augmentation:
    augment_maxlen: 7 # common setting (if no_augment, 0)
    augment_repeatnum: 3 # common setting (if no_augment, 0)
    chara_consecutive_num: 5 # common setting (if no_augment, 0)
    first_consecutive: 0
  image:
    image_streching: True
    background_color: [255, 255, 255] # RGB # common setting
    text_color: [0, 0, 0] # RGB # common setting
    pad_color:  0 # common setting
    load_scale: "gray-scale" # support "gray-scale" or "RGB-scale" # common setting
  audio:
    sampling_rate: 22050 # common setting
    max_wav_value: 32768.0 # common setting
  stft:
    filter_length: 1024 # common setting
    hop_length: 256 # common setting
    win_length: 1024 # common setting
    margin_frame: 5 # common setting
  mel:
    n_mel_channels: 80 # common setting
    mel_fmin: 0 # common setting
    mel_fmax: 8000 # common setting
  energy:
    feature: "element_level"
    normalization: True # common setting