path:
  ckpt_path: "./outputs/RWCP-SSD/latest/ckpt" 
  log_path: "./outputs/RWCP-SSD/latest/log"
  result_path: "./outputs/RWCP-SSD/latest/result"
optimizer:
  batch_size: 12
  betas: [0.9, 0.98] 
  eps: 0.000000001 
  weight_decay: 0.0 
  grad_clip_thresh: 1.0 
  grad_acc_step: 1 
  warm_up_step: 4000 
  anneal_steps: [300000, 400000, 500000] 
  anneal_rate: 0.3 
  init_lr: 0.001 
step:
  total_step: 200000 
  log_step: 100 
  synth_step: 1000 
  val_step: 1000 
  save_step: 10000 
dataparallel: True

use_image: True
image_encoder: False # currently, only False is supported